enableGitInfo = true
# Change baseurl before deploy
baseurl = "https://woodman3.github.io"
languageCode = "en-us"

title = "竹木吟"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "woodman3"

[pagination]
pagerSize = 10


[frontmatter]
# lastmod = [":fileModTime", "lastmod"]
lastmod=['lastmod', ':git', 'date', 'publishDate']
